build:
  image: default-bionic

  environment:
    php:
      version: 8.1.18
      ini:
        xdebug.mode: coverage
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
    my-tests-with-coverage:
      tests:
        override:
          - command: vendor/bin/phpunit --coverage-clover=my-coverage-file
            coverage:
              file: my-coverage-file
              format: php-clover